title: <p align="center"> Niranjan Nagabhushan </p>
logo: /assets/img/pic.jpeg

description: 
  <p align="center">
  <a href="https://www.linkedin.com/feed/update/urn:li:activity:6876459460462813184/">Resume</a> |
  <a href="https://www.linkedin.com/in/niranjannagabhushan/">LinkedIn</a> |
  <a href="https://github.com/niranjannagabhushan">GitHub</a>
  
  <br>
  An Aspiring Data Scientist and Machine Learning Engineer
  <br>
  </p>






theme: jekyll-theme-minimal
