title: <p align="center"> Niranjan Nagabhushan </p>
logo: /assets/img/IMG-20180807-WA0003~01.jpg

description: 
  <p align="center">
  <a href="https://www.linkedin.com/feed/update/urn:li:activity:6876459460462813184/">Resume</a> |
  <ahref="https://www.linkedin.com/in/niranjannagabhushan/">LinkedIn</a> |
  <a href"https://github.com/niranjannagabhushan">GitHub</a>
  
  <br>
  An Aspiring Data Scientist and Artificial Intelligence Engineer
  in search of Knowledge In the Domains of Machine Learning, Deep Learning,
 
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
