title: <p align="center"> Niranjan Nagabhushan </p>
logo: /assets/img/IMG-20180807-WA0003~01.jpg

description: 
  <p align="center">
  <a href="pdf/resume.pdf">Resune</a> |
  <ahref="https://www.linkedin.com/in/niranjannagabhushan/">LinkedIn</a> |
  <a href"https://github.com/niranjannagabhushan">GitHub</a>
  
  <br>
  An Aspiring Data Scientist and Artificial Intelligence Engineer
  in search of Knowledge In the Domains of Machine Learning, Deep Learning,
  NLP and with a background of Electronics And Communication with hopes of Making
  a Career in Data Science and Artificial Intelligence! I am passionate about 
  Data Analysis and identifying the hidden trends and patterns in various types of data!
  Highly Enthusiastic about Artificial Intelligence and Robotics.
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
